/*CREATE DATABASE PI_EAGLE;*/
CREATE DATABASE PI_EAGLE;

USE PI_EAGLE;

CREATE TABLE CADASTRO(
ID INT PRIMARY KEY IDENTITY(1,1),
EMAIL VARCHAR(100) NOT NULL UNIQUE,
NOME VARCHAR(50) NOT NULL,
USUARIO VARCHAR(30) NOT NULL UNIQUE,
SENHA VARCHAR (50) NOT NULL UNIQUE
);


CREATE TABLE LOGAR(
USUARIO VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES CADASTRO(USUARIO),
SENHA VARCHAR (50) NOT NULL FOREIGN KEY REFERENCES CADASTRO(SENHA)
);

CREATE TABLE RECUPERA(
USUARIO VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES CADASTRO(USUARIO),
EMAIL VARCHAR(100) NOT NULL FOREIGN KEY REFERENCES CADASTRO(EMAIL)
);

SELECT * FROM CADASTRO
GO

INSERT INTO CADASTRO VALUES ('TESTE@TESTE2.COM', 'TESTE2', 'TESTE12', 'PASS2')
GO

SELECT * FROM LOGAR;